# Procesamiento_EDA_muestra

El objetivo de este código es procesar y visualizar la muestra de audios de DAIC-WOZ de acuerdo a lo descrito en el trabajo asociado, con la finalidad de poder extraer posteriormente features acústicas y explotarse en modelos predictivos

## 0. Setup
---

In [1]:
import os

import pandas as pd
import librosa

In [2]:
# Path con dataset
path_sample = r'D:\DAIZ-WOZ\base'
# Path salida

# Archivos
path_labels_train = os.path.join(path_sample, 'Docs/train_split_Depression_AVEC2017.csv')
path_labels_dev = os.path.join(path_sample, 'Docs/dev_split_Depression_AVEC2017.csv')
path_labels_test = os.path.join(path_sample, 'Docs/full_test_split.csv')

# Participantes entrevista
name_paciente = 'Participant'
name_entrevistador = 'Ellie'

## 1. Muestra en crudo
---

### 1.1 Carga

In [3]:
# Carga dfs train/dev
df_train = pd.read_csv(path_labels_train)
df_train['split'] = 'train'

df_dev   = pd.read_csv(path_labels_dev)
df_dev['split'] = 'dev'

# Concat de ambos
df_full = pd.concat([df_train, df_dev], ignore_index=True)
df_full

,Participant_ID,PHQ8_Binary,PHQ8_Score,Gender,PHQ8_NoInterest,PHQ8_Depressed,PHQ8_Sleep,PHQ8_Tired,PHQ8_Appetite,PHQ8_Failure,PHQ8_Concentrating,PHQ8_Moving,split
0,303,0,0,0,0,0,0.0,0,0,0,0,0,train
1,304,0,6,0,0,1,1.0,2,2,0,0,0,train
2,305,0,7,1,0,1,1.0,2,2,1,0,0,train
3,310,0,4,1,1,1,0.0,0,0,1,1,0,train
4,312,0,2,1,0,0,1.0,1,0,0,0,0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,483,1,15,1,0,1,3.0,3,3,2,3,0,dev
138,484,0,9,0,1,1,0.0,3,1,2,1,0,dev
139,489,0,3,1,0,1,2.0,0,0,0,0,0,dev
140,490,0,2,1,0,1,0.0,1,0,0,0,0,dev
141,492,0,0,0,0,0,0.0,0,0,0,0,0,dev

In [4]:
# Se filtran columnas de interés y se añade split de test
df_full = df_full[['Participant_ID', 'PHQ8_Binary', 'PHQ8_Score', 'Gender', 'split']]

df_test = pd.read_csv(path_labels_test)
df_test['split'] = 'test'
df_test = df_test.rename(
    columns={
        'PHQ_Binary': 'PHQ8_Binary',
        'PHQ_Score': 'PHQ8_Score'
    }
)

df_full = pd.concat([df_full, df_test], ignore_index=True)

# Formateo columnas
df_full.columns = df_full.columns.str.strip().str.lower()
df_full = df_full.sort_values(by='participant_id').reset_index(drop=True)
df_full

     participant_id  phq8_binary  phq8_score  gender  split
0               300            0           2       1   test
1               301            0           3       1   test
2               302            0           4       1    dev
3               303            0           0       0  train
4               304            0           6       0  train
..              ...          ...         ...     ...    ...
184             488            0           0       0  train
185             489            0           3       1    dev
186             490            0           2       1    dev
187             491            0           8       0  train
188             492            0           0       0    dev

[189 rows x 5 columns]

### 1.2 Cálculo de variables

### 1.3 Visualización

## 2. Procesamiento Muestra
---